title: Karl Griphammar # your name (or website title) here
logo: "/images/small_profile_img.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently MSc student in Applied Data Science at University of Gothenburg, with a background in economics and statistics. My interest lies in making data understandable and useful, 
  and I hope to be able to put my knowledge into good practice.
  I am writing my Master's thesis about improving deep learning networks in Industry 4.0. More specifically, the project is about how deep generative networks can
  be used for improving computer vision used in condition monitoring in production.
  <br><br>
  I also like long-distance running and reading, but having two kids makes this... somewhat of a challenge nowadays. 
  <br><br>
  <a href="https://www.linkedin.com/in/karl-griphammar-4a4690228">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
